from pathlib import Path
import itertools


WORKFLOW = Path("workflow").resolve()
CONFIG = Path("config").resolve()
RESULTS = Path("/scratch/project/bug_seq_scratch/qc_bench/results").resolve()
DATA = Path("/scratch/user/s4897040/biox7021/data").resolve()
FIGURES = RESULTS / "figures"
TABLES = RESULTS / "tables"
LOGS = Path("logs/rules").resolve()

RULES = WORKFLOW / "rules"
ENVS = WORKFLOW / "envs"
BENCHMARK = RESULTS / "benchmark"

configfile: CONFIG / "config.yaml"
pepfile: str(CONFIG / "pep/project_config.yaml")
pepschema: str(CONFIG / "pep/pep_schema.yaml")

SAMPLES = pep.sample_table["sample_name"]
DEPTHS = config["depth"]
MODELS = config["model"]
REPEAT = config["repeat"]

EVAL_TRIMMERS = config["trimming"] + ["untrimmed"]
EVAL_TOOLS = config["quality"] + ["unprocessed"]

KITS = pep.sample_table["sequencing_kits"]


COMBINATIONS = []
for tool in EVAL_TOOLS:
	if tool == "fastplong":
		tool = tool + "-" + "all"
		COMBINATIONS.append(tool)
	else:
		for trimmer in EVAL_TRIMMERS:
			combo = tool + "-" + trimmer
			COMBINATIONS.append(combo)

pr_files = expand(
    RESULTS / "assess/call/{combo}/{depth}x/{model}/{sample}.precision-recall.tsv",
    combo=COMBINATIONS, depth=DEPTHS, sample=SAMPLES, model=MODELS
)

contam_report_files = expand(
    RESULTS / "assess/assembly/contaminant/{combo}/{depth}x/{model}/{sample}.{combo}.contaminants.tsv",
    combo=COMBINATIONS, depth=DEPTHS, sample=SAMPLES, model=MODELS
)

target_files = expand(
    [
        RESULTS / "assess/call/{combo}/{depth}x/{model}/{sample}.precision-recall-summary.tsv",
        RESULTS / "assess/assembly/quast/{combo}/{depth}x/{model}/{sample}.{combo}.report.tsv",
        RESULTS / "assess/assembly/contaminant/{combo}/{depth}x/{model}/{sample}.{combo}.contaminants.tsv"
    ],
    combo=COMBINATIONS, depth=DEPTHS, sample=SAMPLES, model=MODELS
)

rule all:
	input:
		target_files,
		
		FIGURES / "assess/call/metrics/combo_variant_f1.png",
		FIGURES / "assess/call/metrics/combo_variant_recall.png",
		FIGURES / "assess/call/metrics/combo_variant_precision.png",
		TABLES / "assess/call/metrics/combo_variant_summary.csv",
		TABLES / "assess/call/metrics/combo_variant_summary_averages.csv",
		TABLES / "assess/call/metrics/combo_variant_fnfp.csv",
		TABLES / "assess/assembly/metrics/combo_contaminant_summary_count.csv",
		TABLES / "assess/assembly/metrics/combo_contaminant_details.csv",
		TABLES / "assess/assembly/metrics/combo_quast_compiled_metrics.csv",
		FIGURES / "assess/assembly/metrics/combo_assembly_errors_per_100kbp.png",
		FIGURES / "assess/assembly/metrics/combo_assembly_nga50.png",
		FIGURES / "assess/assembly/metrics/combo_assembly_delta_errors.png",
		FIGURES / "assess/assembly/metrics/combo_assembly_delta_nga50.png",
		FIGURES / "assess/call/metrics/combo_variant_delta_fp.png"

include: RULES / "common.smk"
include: RULES / "trim.smk"
#include: RULES / "check.smk"
include: RULES / "quality.smk"
include: RULES / "downsample.smk"
include: RULES / "call.smk"
include: RULES / "assembly.smk"
include: RULES / "assess.smk"

