from pathlib import Path
import itertools


WORKFLOW = Path("workflow").resolve()
CONFIG = Path("config").resolve()
RESULTS = Path("results").resolve()
FIGURES = RESULTS / "figures"
TABLES = RESULTS / "tables"
LOGS = Path("logs/rules").resolve()

RULES = WORKFLOW / "rules"
ENVS = WORKFLOW / "envs"
BENCHMARK = RESULTS / "benchmark"

configfile: CONFIG / "config.yaml"
pepfile: str(CONFIG / "pep/project_config.yaml")
pepschema: str(CONFIG / "pep/pep_schema.yaml")

SAMPLES = pep.sample_table["sample_name"]
TRIMMING = config["trimming"]
FILTERING = config["filtering"]
DEPTHS = config["depth"]
REPEAT = config["repeat"]

KITS = pep.sample_table["sequencing_kits"]

PORECHOP_ABI_SETTINGS = ["nocheck", "discard", "split"]
BARBELL_KIT_SETTINGS = ["default", "max"]

target_files = set()
pr_files= set()
TRIMMING.append("untrimmed")
for trimmer in TRIMMING:
	if trimmer == "porechop_abi":
		for setting in PORECHOP_ABI_SETTINGS:
			current_trimmer = trimmer + "_" + setting
			for depth in DEPTHS:
				for sample in SAMPLES:
					target_files.add(RESULTS / f"assess/mutref/{current_trimmer}/{depth}x/{sample}/{sample}.precision-recall-summary.tsv")
					target_files.add(RESULTS / f"assess/assembly/{current_trimmer}/{depth}x/{sample}/{sample}.{current_trimmer}.report.tsv")
					pr_files.add(RESULTS / f"assess/mutref/{current_trimmer}/{depth}x/{sample}/{sample}.precision-recall.tsv")
	elif trimmer == "barbell":   
		for setting in BARBELL_KIT_SETTINGS: 
			current_trimmer = trimmer + "_" + setting
			for depth in DEPTHS:
				for sample in SAMPLES:
					target_files.add(RESULTS / f"assess/mutref/{current_trimmer}/{depth}x/{sample}/{sample}.precision-recall-summary.tsv")
					target_files.add(RESULTS / f"assess/assembly/{current_trimmer}/{depth}x/{sample}/{sample}.{current_trimmer}.report.tsv")
					pr_files.add(RESULTS / f"assess/mutref/{current_trimmer}/{depth}x/{sample}/{sample}.precision-recall.tsv")
	else:
		for depth in DEPTHS:
			for sample in SAMPLES:
				target_files.add(RESULTS / f"assess/mutref/{trimmer}/{depth}x/{sample}/{sample}.precision-recall-summary.tsv")
				target_files.add(RESULTS / f"assess/assembly/{trimmer}/{depth}x/{sample}/{sample}.{trimmer}.report.tsv")
				pr_files.add(RESULTS / f"assess/mutref/{trimmer}/{depth}x/{sample}/{sample}.precision-recall.tsv")

qends_files = []

for trimmer in TRIMMING:
	if trimmer == "porechop_abi":
		current_trimmer = trimmer + "_" + "nocheck"
		for sample in SAMPLES:
			qends_files.append(RESULTS / f"QC/ends/{current_trimmer}/{sample}.{current_trimmer}.ends.tsv")
	elif trimmer == "barbell":
		for setting in BARBELL_KIT_SETTINGS:
			current_trimmer = trimmer + "_" + setting
			for sample in SAMPLES:
				qends_files.append(RESULTS / f"QC/ends/{current_trimmer}/{sample}.{current_trimmer}.ends.tsv")
	elif trimmer == "dorado":
		current_trimmer1 = trimmer
		current_trimmer2 = trimmer + "_demux"
		for sample in SAMPLES:
			qends_files.append(RESULTS / f"QC/ends/{current_trimmer1}/{sample}.{current_trimmer1}.ends.tsv")
			qends_files.append(RESULTS / f"QC/ends/{current_trimmer2}/{sample}.{current_trimmer2}.ends.tsv")
		
	else:
		for sample in SAMPLES:
			qends_files.append(RESULTS / f"QC/ends/{trimmer}/{sample}.{trimmer}.ends.tsv")

rule all:
	input:
		target_files,
		FIGURES / "assess/mutref/metrics/trimming_variant_f1.png",
		FIGURES / "assess/mutref/metrics/trimming_variant_recall.png",
		FIGURES / "assess/mutref/metrics/trimming_variant_precision.png",
		TABLES / "assess/mutref/metrics/trimming_variant_summary.csv",
		TABLES / "assess/mutref/metrics/trimming_variant_summary_averages.csv",
		FIGURES / "QC/ends/trimming_plot_quality_ends.png",
		TABLES / "assess/mutref/metrics/trimming_variant_fnfp.csv"

include: RULES / "common.smk"
include: RULES / "trim.smk"
include: RULES / "check.smk"
include: RULES / "downsample.smk"
include: RULES / "call.smk"
include: RULES / "assembly.smk"
include: RULES / "assess.smk"

