pepfile: "config/pep/project_config.yaml"
pepschema: "config/pep/pep_schema.yaml"

repeat: 1

depth:
  - 20
  - 50
  - 100

trimming:
  - fastplong
  - porechop_abi
  - dorado
  - barbell

filtering:
  - fastplong
  - filtlong
